import type { CrisisEvent } from '@types';

export const USE_MOCK_DATA = true;

export const MOCK_EVENTS: CrisisEvent[] = [
  {
    id: 'evt-001',
    name: 'Hurricane Helene',
    type: 'hurricane',
    startDate: '2026-05-10T06:00:00Z',
    affectedCounties: ['Galveston', 'Harris', 'Jefferson', 'Chambers'],
    lifelines: {
      'safety-security': {
        id: 'safety-security',
        labelKey: 'lifeline.safety-security.label',
        status: 'major',
        lastUpdated: '2026-05-10T18:30:00Z',
        notes: 'Mass evacuation orders in effect; law enforcement resources stretched across 4 counties',
      },
      'food-hydration-shelter': {
        id: 'food-hydration-shelter',
        labelKey: 'lifeline.food-hydration-shelter.label',
        status: 'major',
        lastUpdated: '2026-05-10T20:00:00Z',
        notes: 'NRG Center at 130% capacity; 3 overflow shelters activated',
      },
      'health-medical': {
        id: 'health-medical',
        labelKey: 'lifeline.health-medical.label',
        status: 'moderate',
        lastUpdated: '2026-05-10T17:45:00Z',
        notes: 'Memorial Hermann and UTMB on backup generators; trauma surge protocol active',
      },
      'water-systems': {
        id: 'water-systems',
        labelKey: 'lifeline.water-systems.label',
        status: 'extreme',
        lastUpdated: '2026-05-10T21:00:00Z',
        notes: 'East Houston treatment plant offline; boil-water advisory for 800k residents',
      },
      energy: {
        id: 'energy',
        labelKey: 'lifeline.energy.label',
        status: 'extreme',
        lastUpdated: '2026-05-10T22:00:00Z',
        notes: '620,000 CenterPoint customers without power; restoration estimated 7–14 days',
      },
      communications: {
        id: 'communications',
        labelKey: 'lifeline.communications.label',
        status: 'moderate',
        lastUpdated: '2026-05-10T19:15:00Z',
        notes: '40% cell tower outage in Galveston County; 911 call volume 5x baseline',
      },
      transportation: {
        id: 'transportation',
        labelKey: 'lifeline.transportation.label',
        status: 'major',
        lastUpdated: '2026-05-10T20:45:00Z',
        notes: 'I-10 East flooded at Channelview; Galveston Causeway closed; 22 county roads impassable',
      },
      'hazardous-material': {
        id: 'hazardous-material',
        labelKey: 'lifeline.hazardous-material.label',
        status: 'moderate',
        lastUpdated: '2026-05-10T22:30:00Z',
        notes: 'Fuel spills at 3 flooded industrial sites in Texas City; TCEQ monitoring active',
      },
    },
    incidents: [
      {
        id: 'inc-001-01',
        title: 'Storm Surge Flooding — Galveston Island',
        type: 'flood',
        affectedLifelines: ['safety-security', 'transportation', 'water-systems'],
        coordinates: [-94.797, 29.301],
        impactRadiusKm: 12,
        severity: 'catastrophic',
        timestamp: '2026-05-10T08:15:00Z',
        description: '10–15 ft storm surge inundating west end; mandatory evacuation zone A fully flooded',
      },
      {
        id: 'inc-001-02',
        title: 'Shelter Overflow — NRG Center',
        type: 'shelter',
        affectedLifelines: ['food-hydration-shelter', 'health-medical'],
        coordinates: [-95.410, 29.685],
        severity: 'high',
        timestamp: '2026-05-10T14:00:00Z',
        description: 'Capacity exceeded; Red Cross activating Toyota Center and George R. Brown as overflow',
      },
      {
        id: 'inc-001-03',
        title: 'Power Grid Failure — CenterPoint Substation 14',
        type: 'power-outage',
        affectedLifelines: ['energy', 'health-medical', 'communications'],
        coordinates: [-95.369, 29.760],
        impactRadiusKm: 8,
        severity: 'high',
        timestamp: '2026-05-10T07:45:00Z',
        description: 'Transmission tower collapse triggering cascading substation failures across central Houston',
      },
      {
        id: 'inc-001-04',
        title: 'Water Treatment Plant Offline — East Houston',
        type: 'water-contamination',
        affectedLifelines: ['water-systems', 'health-medical', 'food-hydration-shelter'],
        coordinates: [-95.122, 29.705],
        impactRadiusKm: 5,
        severity: 'catastrophic',
        timestamp: '2026-05-10T10:30:00Z',
        description: 'Flood water breached primary intake; chlorination offline; boil-water order issued',
      },
      {
        id: 'inc-001-05',
        title: 'Refinery Fuel Spill — Texas City',
        type: 'hazmat',
        affectedLifelines: ['hazardous-material', 'health-medical', 'water-systems'],
        coordinates: [-94.899, 29.386],
        impactRadiusKm: 3,
        severity: 'high',
        timestamp: '2026-05-10T16:20:00Z',
        description: 'Storm surge breached secondary containment; ~40,000 gal diesel released; TCEQ on scene',
      },
      {
        id: 'inc-001-06',
        title: 'Bridge Closure — I-10 Channelview',
        type: 'infrastructure',
        affectedLifelines: ['transportation', 'safety-security'],
        coordinates: [-95.117, 29.780],
        severity: 'high',
        timestamp: '2026-05-10T09:00:00Z',
        description: 'Approach road flooded; TxDOT closed both directions; alternate via US-90',
      },
      {
        id: 'inc-001-07',
        title: 'Civil Unrest — Beaumont Downtown',
        type: 'security',
        affectedLifelines: ['safety-security', 'food-hydration-shelter'],
        coordinates: [-94.102, 30.086],
        impactRadiusKm: 2,
        severity: 'moderate',
        timestamp: '2026-05-10T23:00:00Z',
        description: 'Looting reported at 12 retail locations; curfew enacted 20:00–06:00; JTTF support requested',
      },
    ],
  },
  {
    id: 'evt-002',
    name: 'Placer County Wildfire Complex',
    type: 'wildfire',
    startDate: '2026-05-08T14:30:00Z',
    affectedCounties: ['Placer', 'Nevada', 'El Dorado'],
    lifelines: {
      'safety-security': {
        id: 'safety-security',
        labelKey: 'lifeline.safety-security.label',
        status: 'moderate',
        lastUpdated: '2026-05-09T08:00:00Z',
        notes: 'Evacuation orders covering 18,000 residents; CalFire incident command established Auburn',
      },
      'food-hydration-shelter': {
        id: 'food-hydration-shelter',
        labelKey: 'lifeline.food-hydration-shelter.label',
        status: 'minor',
        lastUpdated: '2026-05-09T10:30:00Z',
        notes: 'Placer County Fairgrounds evacuation center at 78% capacity; 2 secondary sites opening',
      },
      'health-medical': {
        id: 'health-medical',
        labelKey: 'lifeline.health-medical.label',
        status: 'major',
        lastUpdated: '2026-05-09T12:00:00Z',
        notes: 'AQI >500 "Hazardous" in Nevada City; Sutter Roseville burn unit at capacity; N95 distribution active',
      },
      'water-systems': {
        id: 'water-systems',
        labelKey: 'lifeline.water-systems.label',
        status: 'stable',
        lastUpdated: '2026-05-08T18:00:00Z',
        notes: 'Nevada Irrigation District and Placer County Water Agency systems intact',
      },
      energy: {
        id: 'energy',
        labelKey: 'lifeline.energy.label',
        status: 'major',
        lastUpdated: '2026-05-08T20:00:00Z',
        notes: 'PG&E PSPS affecting 45,000 customers; 2 transmission lines damaged by fire; no ETR',
      },
      communications: {
        id: 'communications',
        labelKey: 'lifeline.communications.label',
        status: 'stable',
        lastUpdated: '2026-05-08T16:00:00Z',
        notes: 'AT&T and Verizon coverage intact; FirstNet priority routing active for emergency personnel',
      },
      transportation: {
        id: 'transportation',
        labelKey: 'lifeline.transportation.label',
        status: 'major',
        lastUpdated: '2026-05-09T07:00:00Z',
        notes: 'CA-49 closed Foresthill to Colfax; CA-193 closed; ash and debris on I-80 reducing to 1 lane',
      },
      'hazardous-material': {
        id: 'hazardous-material',
        labelKey: 'lifeline.hazardous-material.label',
        status: 'major',
        lastUpdated: '2026-05-09T09:00:00Z',
        notes: 'Asbestos and lead paint released from 200+ pre-1980 structures; air monitors deployed',
      },
    },
    incidents: [
      {
        id: 'inc-002-01',
        title: 'Primary Fire Front — Foresthill Ridge',
        type: 'wildfire',
        affectedLifelines: ['safety-security', 'energy', 'transportation', 'hazardous-material'],
        coordinates: [-120.822, 39.014],
        impactRadiusKm: 18,
        severity: 'catastrophic',
        timestamp: '2026-05-08T14:30:00Z',
        description: '14,200 acres burning; 0% containment; wind-driven at 35 mph; structures threatened',
      },
      {
        id: 'inc-002-02',
        title: 'Evacuation Center — Placer County Fairgrounds',
        type: 'shelter',
        affectedLifelines: ['food-hydration-shelter', 'health-medical'],
        coordinates: [-121.290, 38.752],
        severity: 'high',
        timestamp: '2026-05-08T16:00:00Z',
        description: '1,850 evacuees registered; American Red Cross and Salvation Army on site; pet shelter annexed',
      },
      {
        id: 'inc-002-03',
        title: 'PSPS Outage — Auburn / Rocklin Corridor',
        type: 'power-outage',
        affectedLifelines: ['energy', 'health-medical', 'food-hydration-shelter'],
        coordinates: [-121.150, 38.850],
        impactRadiusKm: 20,
        severity: 'high',
        timestamp: '2026-05-08T19:30:00Z',
        description: 'PG&E proactive safety shutoff; 45,000 customers; medical baseline customers notified',
      },
      {
        id: 'inc-002-04',
        title: 'Hazmat Release — Auburn Industrial Park',
        type: 'hazmat',
        affectedLifelines: ['hazardous-material', 'health-medical', 'water-systems'],
        coordinates: [-121.077, 38.896],
        impactRadiusKm: 1,
        severity: 'high',
        timestamp: '2026-05-09T06:45:00Z',
        description: 'Paint and solvent warehouse burned; runoff risk to Wolf Creek; Dept of Toxic Substances Control en route',
      },
      {
        id: 'inc-002-05',
        title: 'Road Closure — CA-49 / CA-193 Intersection',
        type: 'infrastructure',
        affectedLifelines: ['transportation', 'safety-security'],
        coordinates: [-121.011, 38.967],
        severity: 'high',
        timestamp: '2026-05-08T17:00:00Z',
        description: 'Fire crossed both highways; CHP closure; evacuation routes redirected via I-80',
      },
      {
        id: 'inc-002-06',
        title: 'Air Quality Emergency — Nevada City',
        type: 'air-quality',
        affectedLifelines: ['health-medical', 'communications', 'food-hydration-shelter'],
        coordinates: [-121.012, 39.262],
        impactRadiusKm: 10,
        severity: 'catastrophic',
        timestamp: '2026-05-09T10:00:00Z',
        description: 'PM2.5 reading 782 µg/m³; shelter-in-place advisory; schools and businesses closed; N95 distribution at fairgrounds',
      },
      {
        id: 'inc-002-07',
        title: 'Structure Loss — Grass Valley Residential Area',
        type: 'wildfire',
        affectedLifelines: ['safety-security', 'hazardous-material', 'health-medical'],
        coordinates: [-121.060, 39.219],
        impactRadiusKm: 4,
        severity: 'high',
        timestamp: '2026-05-09T04:00:00Z',
        description: '47 structures confirmed destroyed; 120+ damaged; asbestos survey teams deployed pre-entry',
      },
    ],
  },
];

export function getMockEvent(id: string): CrisisEvent | undefined {
  return MOCK_EVENTS.find((e) => e.id === id);
}
