import { Amplify } from 'aws-amplify';
// Generated by `ampx sandbox` / `ampx pipeline-deploy`. Gitignored — a local
// stub is created for dev typechecking and overwritten by the real deploy.
import outputs from '../amplify_outputs.json';

Amplify.configure(outputs);

// Function URL of the AGE portal proxy (custom output from backend.ts).
export const AGE_PROXY_URL =
  (outputs as { custom?: { ageProxyUrl?: string } }).custom?.ageProxyUrl ?? '';
